---
title: "RMD - Nota Concurso"
author: "Eduardo Henrique"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```


```{r pacotes}

library(tidyverse)
library(magrittr)
library(readr)
source("R/grafico_barras_qualquer_disciplina.R")
source("R/tema.R")

```


```{r base}

base <- read_csv("../LinguagemR_modulo-21_supportmaterial (Notas_concurso).csv")

write.csv2(base, "data-raw/nota_concurso.csv")

```


```{r inteiro}

# Passando a coluna "Nota" para inteiro:
base$Nota <- as.integer(base$Nota)

```

### Gráfico 1
##### Mostra as 7 melhores notas obtidas pelos alunos em "qualquer disciplina":
```{r grafico1}

base %>%
	mutate(
		Nome_inscricao = paste0(Nome, sep = " - ", "Inscricao ", Inscricao, sep = " - ", Disciplina)
	) %>%
	top_n(7, Nota) %>%
	grafico_melhores(dados = ., coordenadax = Nome_inscricao, coordenaday = Nota) +
	tema()

```

### Gráfico 2
##### Mostra as 7 piores notas obtidas pelos alunos em "qualquer disciplina":
```{r grafico2}

base %>%
	mutate(
		Nome_inscricao = paste0(Nome, sep = " - ", "Inscricao ", Inscricao, sep = " - ", Disciplina)
	) %>%
	top_n(7, desc(Nota)) %>%
	grafico_piores(dados = ., coordenadax = Nome_inscricao, coordenaday = Nota) +
	tema()

```

### Gráfico 3
##### Mostra as 7 melhores notas em Matemática:
```{r grafico3}

base %>%
	mutate(
		Nome_inscricao = paste0(Nome, sep=" - ", "Inscricao ",Inscricao, sep=" - ", Disciplina)
	) %>%
	filter(
		Disciplina == "matematica"
	) %>%
	top_n(7, Nota) %>%
	ggplot() +
	aes(x = reorder(Nome_inscricao, Nota),
			y = Nota) +
	geom_col(fill = "darkblue") +
	geom_label(aes(x = Nome_inscricao, y = Nota, label = Nota), color = "white", fill = "darkblue") +
	labs(x = "Alunos Destaque", y = "Notas", title = "Alunos Destaque em Matemática") +
	coord_flip() +
	tema()

```

### Gráfico 4
##### Mostra as 7 piores notas em Matemática:
```{r grafico4}

base %>%
	mutate(
		Nome_inscricao = paste0(Nome, sep=" - ", "Inscricao ",Inscricao, sep=" - ", Disciplina)
	) %>%
	filter(
		Disciplina == "matematica"
	) %>%
	top_n(7, desc(Nota)) %>%
	ggplot() +
	aes(x = reorder(Nome_inscricao, Nota),
			y = Nota) +
	geom_col(fill = "darkblue") +
	geom_label(aes(x = Nome_inscricao, y = Nota, label = Nota), color = "white", fill = "darkblue") +
	labs(x = "Piores Alunos", y = "Notas", title = "Alunos com as piores Notas em Matemática") +
	coord_flip() +
	tema()

```

